image: golang:1.12

stages:
  - build

build:
  stage: build
  script:
    - GOARCH="amd64" GOOS="linux" go build -mod vendor -o $CI_PROJECT_DIR/terraform-provisioner-awx_linux_amd64
    - GOARCH="amd64" GOOS="windows" go build -mod vendor -o $CI_PROJECT_DIR/terraform-provisioner-awx_x86_64
    - GOARCH="amd64" GOOS="darwin" go build -mod vendor -o $CI_PROJECT_DIR/terraform-provisioner-awx_darwin_amd64
  artifacts:
    paths:
      - terraform-provisioner-awx_linux_amd64
      - terraform-provisioner-awx_windows_x86_64
      - terraform-provisioner-awx_darwin_amd64
